### PR TITLE
Add fractional second support

### PR DESCRIPTION
**Pull request by mhoppal**

### CODE REVIEW

**Comment by craigbr** [comment]
Looks good to me

**Comment by krummas** [comment]
nice, thanks!

**Comment by mhoppal** [comment]
Thanks for merging this so quickly! 

We are wondering if you can cut a new tag 1.4, to be posted on mvn repository, with this new change so we can pull this in with our maven project.

**Comment by krummas** [comment]
I will try to do that tonight/tomorrow

**Comment by mhoppal** [comment]
Hi Marcus,

Have you had a chance to cut a new version with this change included yet?

**Comment by krummas** [comment]
I just did a release - it should show up on mvn central soon

**Pull request merged**
